@apiUrl= http://localhost:3333
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTEzYzZkMS1jNTJmLTRhNWMtYmM5Zi00YzE0YTQyYzBlNTIiLCJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTQzMDU1MDMsImV4cCI6MTcxNDM5MTkwM30.k0AcG70LD8eR_DdUKFj3-bYeclqnGcinIYLMVMn2Kxo

#### User

### Create User
POST {{apiUrl}}/users
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "123456"
}

#### Authentication

###
### Authenticate user with password
# @name Authentication
POST {{apiUrl}}/sessions/password
Accept: application/json
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "123456"
}

###
### Authenticate with github
# @name AuthenticationGithub
# @description Authenticate user with github
# https://github.com/login/oauth/authorize?client_id={{github_client_id}}&redirect_uri=http://localhost:3000/api/auth/callback&scope=user:email
POST {{apiUrl}}/sessions/github
Accept: application/json
Content-Type: application/json

{
  "code": "5876db580b98d22f470b"
}

###
### Authenticate user with token and get profile
GET {{apiUrl}}/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

#### Organization

###
### Create Organization
POST {{apiUrl}}/organization
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Developer Organization",
  "domain": "developer-organization.com",
  "shouldAttachUsersByDomain": true
}

